const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const ICONS={
  save:'<path d="M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11l5 5v11a2 2 0 0 1-2 2Z"/><path d="M17 21v-8H7v8"/><path d="M7 3v5h8"/>',
  'folder-open':'<path d="m6 14 1.5-2.9A2 2 0 0 1 9.24 10H20a2 2 0 0 1 1.94 2.5l-1.54 6A2 2 0 0 1 18.46 20H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h3.9a2 2 0 0 1 1.69.93L12 6h6a2 2 0 0 1 2 2v2"/>',
  moon:'<path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M4.93 19.07l1.41-1.41M17.66 6.34l1.41-1.41"/>',
  hammer:'<path d="m15 12-8.5 8.5L3 17l8.5-8.5"/><path d="m17.64 15 4.61-4.61a1.21 1.21 0 0 0 0-1.72l-5.92-5.92a1.21 1.21 0 0 0-1.72 0L10 7.36"/><path d="m14 4 6 6"/>',
  terminal:'<polyline points="4 17 10 11 4 5"/><line x1="12" x2="20" y1="19" y2="19"/>',download:'<path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" x2="12" y1="15" y2="3"/>',
  'refresh-cw':'<path d="M21 12a9 9 0 0 1-15.5 6.2L3 16"/><path d="M3 21v-5h5"/><path d="M3 12A9 9 0 0 1 18.5 5.8L21 8"/><path d="M21 3v5h-5"/>',
  x:'<path d="M18 6 6 18M6 6l12 12"/>'
};
function icon(name){return `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${ICONS[name]||''}</svg>`}
function applyIcons(){ $$('[data-icon]').forEach(el=>{const n=el.dataset.icon;if(el.tagName==='SPAN')el.innerHTML=icon(n);else if(!el.querySelector('svg'))el.insertAdjacentHTML('afterbegin',icon(n));}); }
applyIcons();

const PERMISSIONS=[['camera','Camera'],['microphone','Microphone'],['notification','Notification'],['location','Location'],['media','Photos and videos'],['contacts','Contacts'],['calendar','Calendar'],['biometrics','Biometrics'],['files','Files and documents'],['bluetooth','Bluetooth / Nearby devices'],['sensors','Sensors']];
const CONTROLS=[['pullRefresh','Pull-Down Refresh'],['hideScrollbars','Hide scrollbars'],['transparentNav','Transparent navigation bar'],['pinchZoom','Pinch to zoom'],['disableCopy','Disable copy text'],['blockAdsRedirects','Block ads & prevent app redirects'],['adguardDns','AdGuard DNS (blocks ads & trackers)']];
const EXTENSIONS=[['adguard','AdGuard AdBlocker'],['ghostery','Ghostery AdBlocker'],['privacyBadger','Privacy Badger'],['darkReader','Dark Reader'],['ublock','uBlock Origin']];
const COMPAT={
  native:{render:{default:1,hardware:1,software:1},permissions:Object.fromEntries(PERMISSIONS.map(([k])=>[k,1])),controls:{pullRefresh:1,hideScrollbars:1,transparentNav:1,pinchZoom:1,disableCopy:1,blockAdsRedirects:1,adguardDns:0},extensions:{}},
  gecko:{render:{default:1,hardware:1,software:0},permissions:Object.fromEntries(PERMISSIONS.map(([k])=>[k,1])),controls:{pullRefresh:0,hideScrollbars:0,transparentNav:1,pinchZoom:1,disableCopy:0,blockAdsRedirects:0,adguardDns:0},extensions:Object.fromEntries(EXTENSIONS.map(([k])=>[k,1]))},
  capacitor:{render:{default:1,hardware:1,software:1},permissions:Object.fromEntries(PERMISSIONS.map(([k])=>[k,1])),controls:{pullRefresh:0,hideScrollbars:0,transparentNav:1,pinchZoom:1,disableCopy:0,blockAdsRedirects:0,adguardDns:0},extensions:{}},
  cordova:{render:{default:1,hardware:1,software:1},permissions:Object.fromEntries(PERMISSIONS.map(([k])=>[k,1])),controls:{pullRefresh:0,hideScrollbars:0,transparentNav:1,pinchZoom:1,disableCopy:0,blockAdsRedirects:0,adguardDns:0},extensions:{}}
};
const state={iconDataUrl:'',splashDataUrl:'',buildId:null,runId:null,poll:null,logPoll:null};
function renderOptions(list,host,group){host.innerHTML=list.map(([id,label])=>`<label class="option" data-option="${id}"><input type="checkbox" value="${id}" data-group="${group}"><span>${label}<small class="support">Ready</small></span></label>`).join('');}
renderOptions(PERMISSIONS,$('#permissionsList'),'permissions'); renderOptions(CONTROLS,$('#controlsList'),'controls'); renderOptions(EXTENSIONS,$('#extensionsList'),'extensions');
function updateCount(){for(const [group,el] of [['permissions','#permissionCount'],['controls','#controlCount'],['extensions','#extensionCount']]){const n=$$(`input[data-group="${group}"]:checked`).length;$(el).textContent=`${n} selected`;}}
$$('.picker input').forEach(x=>x.addEventListener('change',updateCount));
function updateCompat(){const eng=$('#engine').value,c=COMPAT[eng];$$('#renderMode option').forEach(o=>o.disabled=!c.render[o.value]);if($('#renderMode').selectedOptions[0]?.disabled)$('#renderMode').value='default';for(const group of ['permissions','controls','extensions']){$$(`input[data-group="${group}"]`).forEach(i=>{const ok=!!c[group]?.[i.value];i.disabled=!ok;i.closest('.option').classList.toggle('disabled',!ok);i.closest('.option').querySelector('.support').textContent=ok?(group==='extensions'?'GeckoView runtime install':'Supported'):'Not supported by this engine';if(!ok)i.checked=false;});}updateCount();const notes={native:'Native WebView has the widest Website Controls support. AdGuard DNS is disabled because true device-level DNS filtering needs a VPN/DNS layer.',gecko:'GeckoView enables Mozilla-signed Firefox extensions at runtime. Some WebView-only controls are disabled. Extension availability can still depend on Mozilla Add-ons compatibility.',capacitor:'Capacitor uses its stable Android bridge. WebView-specific controls that are not exposed safely are disabled instead of faked.',cordova:'Cordova uses cordova-android 15.1.0. Unsupported native WebView controls are disabled to keep builds deterministic.'};$('#compatNote').textContent=notes[eng];}
$('#engine').addEventListener('change',updateCompat); updateCompat();

function val(id){return $(id).value.trim()} function checked(group){return $$(`input[data-group="${group}"]:checked`).map(x=>x.value)}
function collect(){return {websiteUrl:val('#websiteUrl'),appName:val('#appName'),packageName:val('#packageName'),versionName:val('#versionName'),versionCode:Number($('#versionCode').value),engine:$('#engine').value,renderMode:$('#renderMode').value,orientation:$('#orientation').value,permissions:checked('permissions'),controls:checked('controls'),extensions:checked('extensions'),splashEnabled:$('#splashEnabled').checked,splashDuration:Number($('#splashDuration').value),oneSignalAppId:val('#oneSignalAppId'),offlineFallback:val('#offlineFallback'),iconDataUrl:state.iconDataUrl,splashDataUrl:state.splashDataUrl};}
function applyConfig(c){for(const [k,id] of Object.entries({websiteUrl:'#websiteUrl',appName:'#appName',packageName:'#packageName',versionName:'#versionName',versionCode:'#versionCode',engine:'#engine',renderMode:'#renderMode',orientation:'#orientation',splashDuration:'#splashDuration',oneSignalAppId:'#oneSignalAppId',offlineFallback:'#offlineFallback'}))if(c[k]!=null)$(id).value=c[k];$('#splashEnabled').checked=c.splashEnabled!==false;for(const g of ['permissions','controls','extensions'])$$(`input[data-group="${g}"]`).forEach(i=>i.checked=(c[g]||[]).includes(i.value));state.iconDataUrl=c.iconDataUrl||'';state.splashDataUrl=c.splashDataUrl||'';setPreview('#iconPreview',state.iconDataUrl);setPreview('#splashPreview',state.splashDataUrl);updateCompat();}
function toast(msg,type=''){const e=document.createElement('div');e.className=`toast ${type}`;e.textContent=msg;$('#toasts').append(e);setTimeout(()=>e.remove(),3800)}
function setPreview(sel,url){const e=$(sel);const fallback=sel==='#iconPreview'?'assets/default-icon.png':'assets/default-splash.png';e.style.backgroundImage=`url(${url||fallback})`;e.textContent='';}
async function imageToPng(file,maxW,maxH,quality=.88){if(!file)return'';const img=await createImageBitmap(file);const scale=Math.min(1,maxW/img.width,maxH/img.height);const c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));const ctx=c.getContext('2d');ctx.drawImage(img,0,0,c.width,c.height);img.close?.();return c.toDataURL('image/png',quality);}
$('#iconInput').addEventListener('change',async e=>{try{state.iconDataUrl=await imageToPng(e.target.files[0],512,512);setPreview('#iconPreview',state.iconDataUrl);toast('Icon compressed to PNG','ok')}catch{toast('This image format is not supported by your browser','error')}});
$('#splashInput').addEventListener('change',async e=>{try{state.splashDataUrl=await imageToPng(e.target.files[0],1080,1920);setPreview('#splashPreview',state.splashDataUrl);toast('Splash compressed to PNG','ok')}catch{toast('This image format is not supported by your browser','error')}});
setPreview('#iconPreview',''); setPreview('#splashPreview','');

const presetKey='jepong-apk-presets-v1',historyKey='jepong-apk-history-v1';
function getPresets(){try{return JSON.parse(localStorage.getItem(presetKey)||'[]')}catch{return[]}} function setPresets(x){localStorage.setItem(presetKey,JSON.stringify(x))}
$('#savePresetBtn').addEventListener('click',()=>{const name=prompt('Preset name:','My APK preset');if(!name)return;const arr=getPresets();arr.unshift({id:crypto.randomUUID(),name,createdAt:new Date().toISOString(),config:collect()});setPresets(arr.slice(0,30));toast('Preset saved','ok')});
function showPresets(){const arr=getPresets(),host=$('#presetList');host.innerHTML=arr.length?arr.map(p=>`<div class="preset-item"><div><b>${escapeHtml(p.name)}</b><small>${new Date(p.createdAt).toLocaleString()}</small></div><div><button class="btn small" data-load="${p.id}">Load</button> <button class="btn small" data-del="${p.id}">Delete</button></div></div>`).join(''):'<div class="empty">No saved presets.</div>';host.querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>{const p=getPresets().find(x=>x.id===b.dataset.load);if(p){applyConfig(p.config);$('#presetModal').close();toast('Preset loaded','ok')}});host.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{setPresets(getPresets().filter(x=>x.id!==b.dataset.del));showPresets()});$('#presetModal').showModal();}
$('#loadPresetBtn').onclick=showPresets;$('#closePresets').onclick=()=>$('#presetModal').close();
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function getHistory(){try{return JSON.parse(localStorage.getItem(historyKey)||'[]')}catch{return[]}}function saveHistory(rec){const arr=getHistory().filter(x=>x.buildId!==rec.buildId);arr.unshift(rec);localStorage.setItem(historyKey,JSON.stringify(arr.slice(0,30)));renderHistory()}
function renderHistory(){const arr=getHistory(),host=$('#historyList');host.innerHTML=arr.length?arr.map(x=>`<div class="history-item"><div class="row"><b>${escapeHtml(x.appName||'APK')}</b><span class="state">${escapeHtml(x.conclusion||x.status||'queued')}</span></div><div class="row" style="margin-top:6px"><span>${escapeHtml(x.engine||'')}</span><span>${new Date(x.createdAt).toLocaleString()}</span></div></div>`).join(''):'<div class="empty">No builds yet.</div>';} renderHistory();

function validate(c){const e=[];try{const u=new URL(c.websiteUrl);if(!/^https?:$/.test(u.protocol))e.push('Website URL must use http/https')}catch{e.push('Enter a valid Website URL')}if(!/^[A-Za-z][A-Za-z0-9_]*(\.[A-Za-z][A-Za-z0-9_]*)+$/.test(c.packageName))e.push('Invalid package name');if(!c.appName)e.push('App name is required');if(!Number.isInteger(c.versionCode)||c.versionCode<1)e.push('Version code must be 1 or higher');return e;}
async function startBuild(){const cfg=collect(),errors=validate(cfg);if(errors.length)return toast(errors.join(' · '),'error');$('#successCard').classList.add('hidden');$('#buildState').classList.remove('hidden');$('#buildBtn').disabled=true;$('#progressBar').style.width='2%';$('#progressText').textContent='2%';$('#currentStep').textContent='Sending build configuration';try{const r=await fetch('/api/build-create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(cfg)});const data=await r.json();if(!r.ok)throw new Error(data.error||data.errors?.join(', ')||'Build request failed');state.buildId=data.buildId;$('#buildTitle').textContent=`${cfg.appName} · ${cfg.engine}`;$('#buildSubtitle').textContent=data.buildId;$('#logsBuildId').textContent=data.buildId;saveHistory({buildId:data.buildId,appName:cfg.appName,engine:cfg.engine,status:'queued',createdAt:new Date().toISOString()});pollStatus(cfg);}catch(e){$('#buildState').classList.add('hidden');$('#buildBtn').disabled=false;toast(e.message,'error')}}
$('#buildBtn').onclick=startBuild;
async function pollStatus(cfg){clearInterval(state.poll);const tick=async()=>{try{const r=await fetch(`/api/build-status?buildId=${encodeURIComponent(state.buildId)}`,{cache:'no-store'}),d=await r.json();if(d.error)throw new Error(d.error);state.runId=d.runId||state.runId;const p=Math.max(2,d.progress||2);$('#progressBar').style.width=`${p}%`;$('#progressText').textContent=`${p}%`;$('#currentStep').textContent=d.currentStep||d.status||'Queued';saveHistory({buildId:state.buildId,appName:cfg.appName,engine:cfg.engine,status:d.status||'queued',conclusion:d.conclusion||'',createdAt:new Date().toISOString()});if(d.status==='completed'){clearInterval(state.poll);$('#buildBtn').disabled=false;if(d.conclusion==='success'){setTimeout(()=>{$('#buildState').classList.add('hidden');$('#successCard').classList.remove('hidden');$('#downloadBtn').href=`/api/build-download?runId=${encodeURIComponent(d.runId)}&buildId=${encodeURIComponent(state.buildId)}`;},450)}else{toast(`Build failed: ${d.conclusion||'unknown'}`,'error')}}}catch(e){$('#currentStep').textContent=e.message}};await tick();state.poll=setInterval(tick,3000)}

async function refreshLogs(){if(!state.buildId)return;try{const r=await fetch(`/api/build-logs?buildId=${encodeURIComponent(state.buildId)}`,{cache:'no-store'}),d=await r.json();$('#logsText').textContent=d.text||d.error||'No logs yet.';$('#logsText').scrollTop=$('#logsText').scrollHeight}catch(e){$('#logsText').textContent=e.message}}
$('#logsBtn').onclick=()=>{$('#logsModal').showModal();refreshLogs();clearInterval(state.logPoll);state.logPoll=setInterval(refreshLogs,4000)};$('#closeLogs').onclick=()=>{clearInterval(state.logPoll);$('#logsModal').close()};
$('#refreshHistory').onclick=async()=>{try{const r=await fetch('/api/build-history',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error);for(const x of d.runs||[]){const m=/APK (jpx-[^ ]+) · (\w+)/.exec(x.title||'');if(m)saveHistory({buildId:m[1],appName:m[1],engine:m[2],status:x.status,conclusion:x.conclusion,createdAt:x.createdAt})}toast('History refreshed','ok')}catch(e){toast(e.message,'error')}};
$('#themeBtn').onclick=()=>{document.documentElement.classList.toggle('light');localStorage.setItem('jepong-theme',document.documentElement.classList.contains('light')?'light':'dark');$('#themeBtn').innerHTML=icon(document.documentElement.classList.contains('light')?'sun':'moon')};if(localStorage.getItem('jepong-theme')==='light')document.documentElement.classList.add('light');$('#themeBtn').innerHTML=icon(document.documentElement.classList.contains('light')?'sun':'moon');
